# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 641fe7640723524d4a1b1db931e0cedec47dc268c37c4401511b123c04ee53576318c5c78ab9ba1507493fec013ee59b602b9e62ee1c9bf31c029efaa360c284

test:
  secret_key_base: e0c49d7d5bc14c8bbbe6cc3428fef7d42e1cdf380d48a82690743912e17b828d31093a266c31eff33c5c41776ef3d8577452eb96fd87f8047cd835edd82c409e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
